runtime: nodejs18

env_variables:
  DATABASE_URL: "mongodb+srv://admin:adminuser12345@numero-data.xxwkmsp.mongodb.net/numero-data?retryWrites=true&w=majority"
  PORT: 3232
  SECRET: "dH3u39AO$s>f%yo"
  TOKEN_KEY: "?=G$|nK$/y:gWar"

handlers:
  - url: /.*
    script: auto
    http_headers:
    Access-Control-Allow-Origin: *